services:
  hpatoio_bitly.log.array:
    class: Guzzle\Plugin\Log\LogPlugin
    arguments: ["@hpatoio_bitly.log.adapter.array"]

  hpatoio_bitly.log.adapter.array:
    class: Guzzle\Log\ArrayLogAdapter

  hpatoio_bitly.bitly_data_collector:
    class: Hpatoio\BitlyBundle\DataCollector\BitlyDataCollector
    arguments: ["@hpatoio_bitly.log.adapter.array"]
    tags:
      - { name: data_collector, template: '@HpatoioBitly/Collector/bitly.html.twig', id: "hpatoio_bitly_bundle"  }
